<?php
    include_once "Circle.php";
    Class Cylinder extends Circle{
        public $height;
        public function __construct($color, $radius, $height)
        {
            parent::__construct($color, $radius);
            $this->height = $height;
        }
        public function getHeight(){
            return $this->height;
        }
        public function setHeight($height){
            $this->height = $height;
        }
        public function area()
        {
            return parent::area() + parent::perimeter() * $this->height; // TODO: Change the autogenerated stub
        }
        public function volume(){
            return parent::area() * $this->height;
        }
        public function toString()
        {
            return "Hinh tru, mau $this->color, ban kinh day la $this->radius, chieu cao la $this->height";
        }
    }